#!/bin/sh

files=(~/Pictures/.hiroki/*)
ran=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")

# d option for display #
while getopts "d" option; do
	case $option in
		d) mimeopen -n $ran &
		   copyq copy $(mimetype -b $ran) - < $ran
		   exit;;
		\?) echo "Error: Invalid"
			exit;;
	esac
done

# does copy and info if no -d #
echo -e '\033[1;37m-d for display\033[0m'
copyq copy $(mimetype -b $ran) - < $ran
